;;;;;;;;;;;;CHUONG TRINH DONG HO SO;;;;;;;;;;;;;;
;''''''''''''VIET BOI LU MINH THI''''''''''''''''
;;;;;;;;;;;;;;;;;11/05/2009;;;;;;;;;;;;;;;;;;;;;;
;~~~~~~~~~~~defind~~~~~~~~~~~~~~
S	EQU	37H		;GIAY
M	EQU	38H		;PHUT
T	EQU 39H		;GIO

D_S EQU	40H
D_M EQU	41H
D_T EQU 42H
D_T2 EQU 30H
P_SLE BIT P3.4	;CHON
P_INC BIT P3.5	;GIAM,12/24
BUZZ  BIT P3.7	;GIAM SAT NGUON

APM BIT 00H		;AM/PM
QUA	BIT	01H		;0.25 GIAY
EF1	BIT	03H		;CHO/KO PHEP CHOP PHUT
EF2	BIT	04H		;CHO/KO PHEP CHOP GIO
T24	BIT	05H		;12/24
TEM5 BIT 06H	;BIEN TAM @
ASEC BIT 07H	;1 S
TEM2 EQU  31H	;BIEN TAM
TEM3 EQU  32H	;BIEN TAO XUNG 0.25S
TEM4 EQU  33H	;+++
H24  EQU  35H	;BIEN 24H
C5S	 EQU  36H	;BIEN DEM 5S
;~~~~~~~~BEGIN~~~~~~~~~~~~~~~~~~~
ORG		0000H
JMP		MAIN
ORG		000BH
JMP		SEC
MAIN:
	MOV 43H,#0C0H
	MOV 44H,#0F9H
	MOV 45H,#0A4H
	MOV 46H,#0B0H
	MOV 47H,#099H
	MOV 48H,#092H
	MOV 49H,#082H
	MOV 4AH,#0F8H
	MOV 4BH,#080H
	MOV 4CH,#090H
;~~~~~~~INSTALL~~~~~~~~~~~~~~~~~~~
	MOV IE,#82H		;CHO PHEP NGAT BOI TIMER 0
	MOV TMOD,#01H	;TIMER 0, CHE DO 1
;~~~~~~~12H/AM~~~~~~~~~~~~~~~~~~~
	MOV S,#0
	MOV D_S,#0
	MOV M,#0
	MOV D_M,#0
	MOV T,#12		;12 GIO
	MOV D_T,#12H
	SETB APM		;SANG
	MOV H24,#24		;24 GIO (CHE DO 24H)
	MOV D_T2,#24H
	CLR T24			;TAT CHE DO 24H
;~~~~~~~ORTHER VARIABLE~~~~~~~~~
	MOV C5S,#0		;0 S
	MOV R4,#0		;BIEN DEM TRONG CT NGAT
	MOV TEM3,#0		;0.25S
	CLR EF1			;KO CHOP
	CLR EF2			;KO CHOP
	SETB BUZZ
	MOV P3,#0FFH
	SETB TF0
;~~~~~~~~CHUONG TRINH CHINH~~~~~
REPEAT:
	JNB BUZZ,EX_DISP
	CLR EF1
	CLR EF2
	JNB P_SLE,SUBB_SLE
	JNB P_INC,SUBB_INC
	CALL DISP
EX_DISP:
	JMP REPEAT
;~~~~~~~~~NHAY NOI TIEP~~~~~~~~~~~~~~~~~~
SUBB_SLE:
		JMP SUB_SLE
SUBB_INC:
		JMP SUB_INC
;~~~~~~~~~~KEYBOARD~~~~~~~~~~~~~~~~~~~~~~~~
;;;;;;;;;;;DIEU CHINH PHUT;;;;;;;;;;;;;;;;;
SUB_SLE:
		SETB	EF1
		CLR		EF2
RE_SLE:
		CALL DISP
		JNB P_INC,SET_TIME
		JNB P_SLE,RE_SLE
RETURN1:
		JNB P_SLE,SUB1_SLE
		JNB P_INC,SUB1_INC
		CALL DISP
		MOV R2,#60
		CLR TEM5
		JMP RETURN1
;;;;;;;;;;;LOA;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SET_TIME:
		CPL BUZZ
RE_SET:
		CALL DISP
		JNB P_INC,$-3
		JNB P_SLE,RE_SET
		JMP REPEAT
		
SUB1_INC:
		MOV A,M
		ADD A,#1
		MOV M,A
		DA A
		MOV D_M,A
		CJNE A,#60H,EX1_INC
		MOV D_M,#0
		MOV M,#0
;~~~~~~~~~~~TANG CO (GIU)~~~~~~~~~~~~~~~~~~~~~~~
EX1_INC:
		JB P_INC,REPEAT_INC
		JB TEM5,REPEAT_DISP
REPEAT_INC:
		DJNZ R2,$+6
		SETB TEM5
		JMP SUB1_INC
		CALL DISP
		JNB P_INC,REPEAT_INC
		JMP RETURN1
		
REPEAT_DISP:
		PUSH 01H
		MOV R1,#5
DISP_RE:
		CALL DISP
		DJNZ R1,DISP_RE
		POP 01H
		JMP SUB1_INC		
;;;;;;;;;DIEU CHINH GIO;;;;;;;;;;;;;;;;;
SUB1_SLE:
		SETB 	EF2
		CLR		EF1
		CALL DISP
		JNB P_SLE,$-3
RETURN2:
		JNB P_SLE,SUB2_SLE
		JNB P_INC,SUB2_INC
		CALL DISP
		JMP RETURN2
SUB2_INC:
		MOV A,T
		ADD A,#1
		MOV T,A
		DA A
		MOV D_T,A
		CJNE A,#12H,TT_INC
		CPL APM
TT_INC:
		CJNE A,#13H,EX2_INC
		MOV D_T,#1
		MOV T,#1
EX2_INC:
		CALL DISP
		JNB P_INC,$-3
		JMP RETURN2
SUB2_SLE:
		CALL DISP
		JNB P_SLE,$-3
		JMP REPEAT
;;;;;;;;;CHE DO 24H/APM;;;;;;;;;;;;;;;;;;;;;;;
SUB_INC:
		CPL T24
		CALL DISP
		JNB P_INC,$-3
		JMP REPEAT
;~~~~~~~~~~~DISPLAY~~~~~~~~~~~~~~~~~~~~~~~~
DISP:
	JNB EF1,NOF1
	JB QUA,EXIT_DISP1
NOF1:
	MOV A,D_M
	ANL A,#0FH
	ADD A,#43H
	MOV R0,A
	MOV P1,@R0
	JNB T24,TIP_T24
	MOV C,QUA
	MOV P1.7,C
	JMP EXIT_T24
TIP_T24:
	MOV C,APM
	MOV P1.7,C
EXIT_T24:
	CLR P3.3
	CALL DELAY2MS
	SETB P3.3
	MOV P1,#00H
	MOV A,D_M
	SWAP A
	ANL A,#0FH
	ADD A,#43H
	MOV R0,A
	MOV P1,@R0
	JNB ASEC,CROS1
	CLR P1.7
CROS1:	
	CLR P3.2
	CALL DELAY2MS
	SETB P3.2
	MOV P1,#00H
	JMP EXIT_M
EXIT_DISP1:
	CALL DELAY2MS
	CALL DELAY2MS
EXIT_M:
	JNB EF2,NOF2
	JB QUA,EXIT_DISP2
NOF2:
	JB T24,HT24H
	MOV TEM2,D_T		;HIEN THI GIO
	JMP HTAPM
HT24H:
	MOV TEM2,D_T2
HTAPM:
	MOV A,TEM2
	ANL A,#0FH
	ADD A,#43H
	MOV R0,A
	MOV P1,@R0
	JNB ASEC,CROS2
	CLR P1.7
CROS2:
	CLR P3.1
	CALL DELAY2MS
	SETB P3.1
	MOV P1,#00H
	MOV A,TEM2
	SWAP A
	ANL A,#0FH
	ADD A,#43H
	MOV R0,A
	MOV P1,@R0
	CLR P3.0
	CALL DELAY2MS
	SETB P3.0
	MOV P1,#00H
	JMP EXIT_T
EXIT_DISP2:
	CALL DELAY2MS
	CALL DELAY2MS
EXIT_T:

	RET
;~~~~~~~~~~COMPARE~~~~~~~~~~~~~~~~~~~~~~~~~

;~~~~~~~~~~DELAY2ms~~~~~~~~~~~~~~~~~~~~~~~~
DELAY2MS:
	PUSH 00H
	PUSH 01H
	MOV R0,#30
REPEAT_2MS:
	MOV R1,#100
	DJNZ R1,$
	DJNZ R0,REPEAT_2MS
	POP 01H
	POP 00H
	RET
;;;;;;;;;;;NOI TIEP;;;;;;;;;;;;;;;;;;;;;;;
END_SEC2:
	JMP END_SEC
;~~~~~~~~CHUONG TRINH NGAT~~~~~~~~~~~~~~~~~
SEC:
	PUSH ACC
	MOV TL0,LOW(-49988)
	MOV TH0,HIGH(-49988)
	SETB TR0
	INC R4
	INC TEM3
	MOV A,TEM3
	CJNE A,#5,EXIT_QUA
	CPL QUA
	MOV TEM3,#0
EXIT_QUA:
	CJNE R4,#20,END_SEC2
	MOV R4,#0
;~~~~~~~~~~~COUT/AM/PM/24~~~~~~~~~~~~~~~~~
COUT:
	CPL ASEC
	INC C5S
	MOV A,C5S
	CJNE A,#5,EX_C5S
	SETB BUZZ
	MOV C5S,#0
EX_C5S:
	MOV A,S
	ADD A,#1
	MOV S,A
	DA A
	MOV D_S,A
	CJNE A,#60H,EXIT_SEC
	MOV S,#0
	MOV A,M
	ADD A,#1
	MOV M,A
	DA A
	MOV D_M,A
	CJNE A,#60H,EXIT_SEC
	MOV M,#0
	MOV A,T
	ADD A,#1
	MOV T,A
	DA A
	MOV D_T,A
	CJNE A,#13H,EXIT_SE
	MOV T,#1
	JMP EXIT_SEC
EXIT_SE:
	CJNE A,#12H,EXIT_SEC
	CPL APM
	JNB APM,EXIT_SEC
EXIT_SEC:
	MOV A,D_T
	JNB APM,CONV24
	CJNE A,#12H,CONV224
	MOV A,T
	ADD A,#12
	MOV H24,A
	DA A
	MOV D_T2,A
	JMP END_SEC
CONV224:
	MOV A,T
	CJNE A,#11,TIP7
	MOV H24,T
	MOV D_T2,#11H
	JMP END_SEC
TIP7:
	CJNE A,#10,TIP8
	MOV H24,T
	MOV D_T2,#10H
	JMP END_SEC
TIP8:
	MOV H24,T
	MOV D_T2,T
	JMP END_SEC
CONV24:
	CJNE A,#12H,CONV225
	JMP CONV224
CONV225:
	MOV A,T
	ADD A,#12
	MOV H24,A
	DA A
	MOV D_T2,A
END_SEC:
	POP ACC
	RETI
END