;::::::LU MINH THI:::::::::
;:::::22/06/2009:::::::::::
ORG 0
MAIN:
;;;;;;;;;KHOI TAO;;;;;;;;;;;
MOV TMOD,#20H					;BO DINH THOI 1 CHE DO 2
MOV SCON,#52H					;NOI TIEP CHE DO 1, KHONG CHO PHEP PHAT
MOV TH1,#-3						;TOC DO BAUD=9600
SETB TR1						;UART SAN SANG
MOV R0,#0						;XOA R0
SETB P1.0						;DAT BIT P1.0=1
CLR P2.0						;KHONG CHO PHEP MODULE PHAT
;;;;;;;;BAT DAU;;;;;;;;;;;;;
RETURN:
		JNB P1.0,CONTINUE		;KIEM TRA P1.0 BANG 0 CHUA
		MOV R0,#0				;XOA R0 NEU P0.1 TRO VE 1
		JMP RETURN				;<>
CONTINUE:
		MOV A,#0
		MOV R1,#0
		MOV DPTR,#LMT
REP_T:		
		MOVC A,@A+DPTR
		CALL DELAY100MS			;TRI HOAN 100MS
		INC R0					;<>
		CJNE R0,#1,RETURN		;DUOC 10 LAN CHUA?
		MOV R0,#0				;XOA R0
		SETB P2.0				;CHO PHEP MODULE PHAT
		JNB TI,$				;TRUYEN XONG CHUA?
		CLR TI					;SAN SANG PHAT
		MOV SBUF,A				;TRUYEN
		INC R1
		MOV A,R1
		CJNE R1,#11,REP_T
		JMP RETURN
;:::::::::TRE 100MS, THACH ANH 11.0592MHZ:::::::::
DELAY100MS:
		PUSH 01H
		PUSH 00H
		MOV R0,#200
REP_DELAY100MS:
		MOV R1,#250
		DJNZ R1,$
		DJNZ R0,REP_DELAY100MS
		POP 00H
		POP 01H
		RET
lmt:
DB	"LU MINH THI",0
END