;////////////////CHUONG TRINH PHAT XUNG PWM P1.0 ///////////////////////////////////
;///////////////////////////LU MINH THI ////////////////////////////////////////////
;////////////////////////////25-02-2010/////////////////////////////////////////////
;KHAI BAO
XLOW1 DATA 30H
XHIG1 DATA 31H
XLOW2 DATA 32H
XHIG2 DATA 33H
TEM DATA 20H
WAR1 BIT TEM.0
ORG 0
JMP BEGIN
;PHAT XUNG PWM
ORG 000BH
	CPL P1.0
	JNB WAR1,SECON1
	MOV TL0,XLOW1
	MOV TH0,XHIG1
	CLR WAR1
	CLR TF0
	RETI
SECON1:
	MOV TL0,XLOW2
	MOV TH0,XHIG2
	SETB WAR1
	CLR TF0
	RETI
;KHOI TAO
BEGIN:
	MOV TMOD,#00H
	MOV IE,#82H
	SETB P3.2
	SETB P3.3
	SETB P1.0
	MOV XLOW1,#LOW(-1)
	MOV XHIG1,#HIGH(-1)
	MOV XLOW2,#LOW(-8191)
	MOV XHIG2,#HIGH(-8191)
	SETB TR0
	SETB TF0
	JMP $
;CHUONG TRINH CHINH
MAIN:
	JNB P3.2,TANG
	JNB P3.3,GIAM
	JMP MAIN
TANG:
	MOV A,XLOW1
	CJNE A,#254,CONT_TANG
	JMP EX_TANG
CONT_TANG:
	INC XLOW1
	CALL CONTRO1
EX_TANG:
	JNB P3.2,$
	JMP MAIN
GIAM:
	MOV A,XLOW1
	CJNE A,#1,CONT_GIAM
	JMP EX_GIAM
CONT_GIAM:
	DEC XLOW1
	CALL CONTRO1
EX_GIAM:
	JNB P3.3,$
	JMP MAIN

;DIEU CHINH DO RONG XUNG 1 - 255 KENH 1
CONTRO1:
	PUSH ACC
	MOV A,XLOW1
	CPL A
	ADD A,#1
	MOV XHIG1,A
	POP ACC
	RET
END