;////////////////CHUONG TRINH PHAT XUNG PWM P1.0 ///////////////////////////////////
;///////////////////////////LU MINH THI ////////////////////////////////////////////
;////////////////////////////25-02-2010/////////////////////////////////////////////
;KHAI BAO
XLOW DATA 30H
XHIG DATA 31H
TEM DATA 20H
WAR1 BIT TEM.0
ORG 0
JMP BEGIN
;PHAT XUNG PWM 3.7KHZ KENH 1
ORG 0001BH
	MOV P0,#0
	JNB WAR1,SECON1
	MOV TL1,XHIG
	CLR WAR1
	RETI
SECON1:
	MOV P0,#255
	MOV TL1,XLOW
	SETB WAR1
	RETI
;KHOI TAO
BEGIN:
	MOV TMOD,#20H
	MOV IE,#88H
	SETB P1.0
	MOV XLOW,#127
	CALL CONTROL
	SETB TR1
	SETB TF1
;CHUONG TRINH CHINH
MAIN:

	MOV XLOW,#1
	CALL CONTROL
	CALL DELAY 
	CALL DELAY
	MOV XLOW,#255
	CALL CONTROL
	CALL DELAY
	CALL DELAY
	JMP MAIN

LOOP_GIAM:
	MOV A,XLOW
	CJNE A,#1,GIAM
	JMP LOOP_TANG
GIAM:

	DEC XLOW
	CALL CONTROL
	CALL DELAY
	SJMP LOOP_GIAM
LOOP_TANG:
	MOV A,XLOW
	CJNE A,#255,TANG
	SJMP LOOP_GIAM
TANG:
	INC XLOW
	CALL CONTROL
	CALL DELAY
	JMP LOOP_TANG
	JMP MAIN

;DIEU CHINH DO RONG XUNG 1 - 255 KENH 1
CONTROL:
	PUSH ACC
	MOV A,XLOW
	CPL A
	ADD A,#1
	MOV XHIG,A
	POP ACC
	RET
DELAY:
	PUSH 00H
	PUSH 01H
	MOV R0,#255
LOOP_DELAY:
	MOV R1,#255
	DJNZ R1,$
	DJNZ R0,LOOP_DELAY
	POP 01H
	POP 00H
	RET
END