;DEFINE
SDA	BIT P0.1
SCL BIT P0.0
SQW BIT P0.2

WIRTE	EQU		0D0H
READ	EQU		0D1H

_SEC	DATA	30H
_MIN	DATA	31H
_HOUR	DATA	32H
_DAY	DATA	33H
_MONT	DATA	33H
_YEAR	DATA	34H
_CONT	DATA	35H

TEMP	DATA	36H
ADDR	DATA	37H
BYTES	DATA	38H
INDEX	DATA	39H

ORG 0
MAIN:
		MOV 40H,#00010000B
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#07H
		MOV INDEX,#40H
		CALL MASTER_W
		MOV R7,#20
L_MAIN:
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#00H
		MOV INDEX,#30H
		CALL MASTER_R
		MOV P2,30H
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#01H
		MOV INDEX,#31H
		CALL MASTER_R
		MOV P3,31H
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#02H
		MOV INDEX,#32H
		CALL MASTER_R
		MOV P1,32H
		DJNZ R7,L_MAIN
		MOV R7,#20
L2_MAIN:
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#04H
		MOV INDEX,#33H
		CALL MASTER_R
		
		MOV P1,33H
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#05H
		MOV INDEX,#34H
		CALL MASTER_R
		MOV P3,34H
		CALL DELAY100M
		MOV BYTES,#01H
		MOV ADDR,#06H
		MOV INDEX,#35H
		CALL MASTER_R
		MOV P2,35H
		DJNZ R7,L2_MAIN
		
		JMP MAIN
;DOC DU LIEU TU DS1307 VOI CAC THAM SO: BYTES(SO BYTES DUOC DOC LIEN TIEP),INDEX(DIA CHI DICH 8051),ADDR(DIA CHI NGUON DS1307 )	
MASTER_R:
		PUSH 00H
		PUSH 07H
		CALL SELECT_ADDR
		CALL CON_S
		MOV TEMP,#READ
		CALL __BYTE_WIRTE	
		MOV R7,BYTES
		MOV R0,INDEX
__LOOP4:
		CALL ACK
		CALL __BYTE_READ
		MOV @R0,TEMP
		INC R0
		DJNZ R7,__LOOP4
		CALL N_ACK
		CALL CON_P
		POP 07H
		POP 00H
		RET
;GHI DU LIEU LEN DS1307 VOI CAC THAM SO: BYTES(SO BYTES DUOC GHI LIEN TIEP),INDEX(DIA CHI DU LIEU NGUON 8051),ADDR(DIA CHI DICH DS1307)
MASTER_W:
		PUSH 07H
		PUSH 00H
		CALL CON_S
		MOV TEMP,#WIRTE
		CALL __BYTE_WIRTE
		CALL ACK
		MOV TEMP,ADDR
		CALL __BYTE_WIRTE
		CALL ACK
		MOV R7,BYTES
		MOV R0,INDEX
LOOP3__:
		MOV A,@R0
		INC R0
		MOV TEMP,A
		CALL __BYTE_WIRTE
		CALL ACK
		DJNZ R7,LOOP3__
		CALL CON_P
		POP 00H
		POP 07H
		RET
;DINH CON TRO DU LIEU QUA ADDR		
SELECT_ADDR:
		CALL CON_S
		MOV TEMP,#WIRTE
		CALL __BYTE_WIRTE
		CALL ACK
		MOV TEMP,ADDR
		CALL __BYTE_WIRTE
		CALL ACK
		CALL CON_P
		RET
;PHAT 1BYTE DU LIEU TRONG TEMP

__BYTE_WIRTE:
		PUSH 07H
		MOV A,TEMP
		MOV R7,#8
LOOP1__:
		RLC A
		MOV SDA,C
		SETB SCL
		CALL DELAYP
		CLR SCL
		DJNZ R7,LOOP1__
		POP 07H
		RET
; NHAN 1 BYTE DU LIEU CAT VAO TEMP
__BYTE_READ:
		PUSH 07H
		MOV R7,#8
LOOP2__:	
		SETB SCL
		MOV C,SDA
		CALL DELAYP
		CLR SCL
		RLC A
		DJNZ R7,LOOP2__
		MOV TEMP,A
		POP 07H
		RET
; DIEU KIEN START
CON_S:
		SETB SDA
		SETB SCL
		CALL DELAYN
		CLR SDA
		CALL DELAYN
		CLR SCL
		RET
;DIEU KIEN STOP
CON_P:
		CLR SDA
		CLR SCL
		CALL DELAYN
		SETB SCL
		CALL DELAYN
		SETB SDA
		RET
;BAO DA NHAN/PHAT 1 BYTE
ACK:
		CLR SCL
		CLR SDA
		CALL DELAYP
		SETB SCL
		CALL DELAYP
		CLR SCL
		SETB SDA
		CALL DELAYP
		RET
;DAO CUA ACK
N_ACK:
		CLR SCL
		SETB SDA
		CALL DELAYP
		SETB SCL
		CALL DELAYP
		RET
;LONG DELAY
DELAY100M:
		PUSH 07H
		PUSH 06H
		MOV R7,#200
RE_DELAY100M:
		MOV R6,#249
		DJNZ R6,$
		DJNZ R7,RE_DELAY100M
		POP 06H
		POP 07H
		RET
		
;SHORT DELAY
DELAYP:
		NOP
		NOP
		RET
DELAYN:
		PUSH 07H
		MOV R7,#5
		DJNZ R7,$
		POP 07H
		RET
		
END