KA	BIT 00H
ORG 0
	MOV SCON,#50H		;CHE DO 1,CHO PHEP NHAN
	MOV TMOD,#20H		;BO DINH THOI 1 CHE DO 2 (NAP LAI)
	MOV TH1,#-3			;TOC DO BAUD=9600
	SETB TR1			;KHOI DONG URART
;;;;;;;;;;;;;;;;;;;
REPEAT2:
	CPL KA
	MOV A,#0FFH
	MOV P2,A
	CALL DELAY
REPEAT1:
	JNB RI,CONTINUE		;NEU KHONG NHAN THI CHAY LED
	MOV P2,SBUF
	CLR RI
	CALL DELAY6S		;
	MOV A,#0FFH
CONTINUE:
	CLR C
	JNB KA,CONT_R
	RLC A
	JMP CONT_L
CONT_R:
	RRC A
CONT_L:
	MOV P2,A
	CALL DELAY
	CJNE A,#0,REPEAT1
	JMP REPEAT2
;;;;;;;;;;;;;;;;;;;;;
DELAY:
		MOV R1,#250
REP_DELAY:
		MOV R2,#250
		DJNZ R2,$
		DJNZ R1,REP_DELAY
		RET
;;;;;;;;;;;;;;;;;;;	
DELAY6S:
		MOV R3,#100
REP_DELAY6S:
		CALL DELAY
		DJNZ R3,REP_DELAY6S
		RET	
END